### ISSUE TITLE
Wrath Classic error

### ISSUE THREAD

**Issue by Brum8842** [tvlfrosty/Reputation_Guide#13]
Getting an error the reps tab doesn't show anything 

Date: 2022-08-31 16:35:38
ID: 8
Error occured in: Global
Count: 2
Message: ..\AddOns\ReputationGuide\ReputationGuide.lua line 4620:
   attempt to index local 'factionHeader' (a nil value)
Debug:
   [string "@ReputationGuide\ReputationGuide.lua"]:4620: OriginalRepOrderWithFactionHeader()
   [string "@ReputationGuide\ReputationGuide.lua"]:1823: ReputationFrame_Update()
   [string "*:OnEvent"]:4:
      [string "*:OnEvent"]:1
Locals:
self = <table> {
 Update_Tooltip = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:2231
 SupressNone = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:2201
 zone = <table> {
 }
 About = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:994
 SortByStandingWithoutFactionHeader = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:4112
 GetTabardFaction = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1221
 GetReadyReputation = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3350
 DumpTable = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:355
 has_value = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:967
 InitFactionMap = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1302
 Rep_Detail_Frame = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3599
 ToggleDarkmoonFaireBuff = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:623
 GetWords = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:924
 RepItems = <table> {
 }
 InitMobName = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1088
 ExtractSkills = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3794
 Quest_Items = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:2858
 OriginalRepOrderWithFactionHeader = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:4613
 SortByStandingWithFactionHeader = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:4480
 OriginalRepOrderWithoutFactionHeader = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:4301
 ListByStanding = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3753
 StandingSort = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3474
 InitFactor = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1239
 Print = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:880
 DumpReputationChangesToChat = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3085
 BoolToEnabled = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:956
 ToggleDetailWindow = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3271
 Debug = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:910
 InitMapName = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1038
 Quest_Names = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1161
 TableSize = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:915
 ClearSessionGain = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:3195
 ShowUpdateEntry = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:2946
 GetUpdateListSize = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:2930
 InitFaction = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1292
 MakeUIChanges = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:612
 Init = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:390
 UpdateEntrySuppress = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:2176
 BuildUpdateList = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:2237
 PrintSlash = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:905
 Printtest = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:901
 Help = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:980
 Status = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:1015
 Concat = <function> defined @Interface\AddOns\ReputationGuide\ReputationGuide.lua:940
 InitVariab

**Comment by tvlfrosty** [comment]
Releasing a fix for wotlk error as we speak!

**Comment by Brum8842** [comment]
ok thanks

**Comment by tvlfrosty** [comment]
Fix should be on curse now, shouldn't matter what version if the curseforge client isn't updated yet for Wrath classic

**Comment by tvlfrosty** [comment]
Should have been fixed with #14
