### ISSUE TITLE
LUA Error on login enUS Retail WoW

### ISSUE THREAD

**Issue by Jaladhjin** [tvlfrosty/Reputation_Guide#15]
4x ReputationGuide\ReputationGuide-9.2.7.1-release.lua:1493: bad argument #1 to 'lower' (string expected, got nil)
[string "=[C]"]: in function `lower'
[string "@ReputationGuide\ReputationGuide-9.2.7.1-release.lua"]:1493: in function `REP_AddQuest'
[string "@ReputationGuide\content.lua"]:2122: in function `REP_InitEnFactionGains'
[string "@ReputationGuide\ReputationGuide-9.2.7.1-release.lua"]:597: in function `Init'
[string "@ReputationGuide\ReputationGuide-9.2.7.1-release.lua"]:332: in function `REP_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

Thought you might like to know 😁👍

**Comment by tvlfrosty** [comment]
Just pushed an update for retail, appeared to be an issue on horde side I missed, appologies!
