### ISSUE TITLE
LUA bug in Wrath

### ISSUE THREAD

**Issue by Gogo1951** [tvlfrosty/Reputation_Guide#17]
2x ReputationGuide\ReputationGuide-3.4.0.3-release.lua:1493: bad argument #1 to 'lower' (string expected, got nil)
[string "=[C]"]: in function `lower'
[string "@ReputationGuide\ReputationGuide-3.4.0.3-release.lua"]:1493: in function `REP_AddQuest'
[string "@ReputationGuide\content.lua"]:1652: in function `REP_InitEnFactionGains'
[string "@ReputationGuide\ReputationGuide-3.4.0.3-release.lua"]:597: in function `Init'
[string "@ReputationGuide\ReputationGuide-3.4.0.3-release.lua"]:258: in function `REP_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by tvlfrosty** [comment]
Should be fixed in the latest release on curse, which is currently being processed!
