### ISSUE TITLE
Showing wrong Rep @Shadowlands

### ISSUE THREAD

**Issue by Scaver** [tvlfrosty/Reputation_Guide#20]
Client Language: German

3 factrions showing the wrong rep in SL:
Der Archivarskodex (The Archivists' Codex)
Hof der Nacht (Court of Night)
Ve'nari

Here a screen. It is better than to describe it.
![RepScreen](https://user-images.githubusercontent.com/9563058/188918007-09a7bf75-ba8b-4c05-97e8-c9e5ec19ed94.png)

**Comment by tvlfrosty** [comment]
I will take a look at this tonight, it's been a busy week, appologies!

**Comment by Scaver** [comment]
Thanks and no need to appologies.

**Comment by tvlfrosty** [comment]
This should be fixed in the later releases. If there is still problems with names, please let me know!
