### ISSUE TITLE
Fix Chromie being in Revered section and not in Exalted

### ISSUE THREAD

**Issue by bernardthibaut** [tvlfrosty/Reputation_Guide#30]
Hi!

I finished the Chromie reputation but when I sort all the reputations, this one is listed in the Revered section and not in the Exalted one.
Could you change that please ?

Thanks for your work ;)

Here is a screenshot of the issue (in French):

![reputation_chromie_issue](https://user-images.githubusercontent.com/11993565/197788142-e654e7e4-4b23-4e51-99a6-7b7db15dcb28.png)

**Comment by tvlfrosty** [comment]
Seeing as the SortByStanding functionality is completely broken/turned off atm, I added this to the #29 list, as it might be part of the factions that have less than 8 Standings, looks like Chromie has 7 instead of 8.
