### ISSUE TITLE
Wotlk 3.4.1 REP_HiddenQuestTooltip:SetHyperlink(): Unknown link type

### ISSUE THREAD

**Issue by Brum8842** [tvlfrosty/Reputation_Guide#35]
Hi I am getting this error whenever I click on a faction rep, the window is all blank

Message: Interface/AddOns/ReputationGuide/ReputationGuide.lua line 1209:
   REP_HiddenQuestTooltip:SetHyperlink(): Unknown link type

Debug:
   [string "=[C]"]: SetHyperlink()
   [string "@Interface/AddOns/ReputationGuide/ReputationGuide.lua"]:1209: Quest_Names()
   [string "@Interface/AddOns/ReputationGuide/ReputationGuide.lua"]:2489: BuildUpdateList()
   [string "@Interface/AddOns/ReputationGuide/ReputationGuide.lua"]:2011: ReputationBar_OnClick()
   [string "*ReputationFrame.xml:212_OnClick"]:1:
      [string "*ReputationFrame.xml:212_OnClick"]:1

Locals:
(*temporary) = REP_HiddenQuestTooltip {
 SetBorderBlendMode = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:203
 NineSlice = Frame {
 }
 TooltipBackdropOnLoad = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:172
 TopOverlay = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:191
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:199
 0 = <userdata>
 BottomOverlay = Texture {
 }
 SetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:187
 layoutType = "TooltipDefaultLayout"
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:195
}
(*temporary) = "quest:12761"

**Comment by tvlfrosty** [comment]
Getting the error when updating to interfac 3.4.1, I will look into it.
