### ISSUE TITLE
More detailed info in description

### ISSUE THREAD

**Issue by tflo** [tvlfrosty/Reputation_Guide#4]
In your description (on Curseforge), you say “This addon is based on the addon RepHelper”, but you don’t say what the differences/improvements are compared to RepHelper.

RepHelper is still working fine for me (or at least I think so ;), so a bit more information on that would help me to decide if I should give your addon a try.

Thank you

– Tom

**Comment by tvlfrosty** [comment]
Hey,

Good point!

I added some extra information to the description on Curseforge,

And you are correct, the RepHelper addon does still work for the current versions of the game, it's however out-dated and no longer being updated anymore.

The current Classic version will break as soon Classic Wotlk is released as the Reputation interface was changed and so were the api's that were being used to get data about the factions.

I  hope the additional description clears it up for you.


I will update the description in Github later today as well to keep them both up to date with eachother, so if you think something is missing please let me know.


Thanks for the feedback!

Tom (Tvlfrosty - Firemaw)

**Comment by tflo** [comment]
> I hope the additional description clears it up for you.

Yep, totally cleared up now :) 

(And already installed.)

Thanks!
