### ISSUE TITLE
ReputationGuide.lua:3372: table index is nil

### ISSUE THREAD

**Issue by Ookami313** [tvlfrosty/Reputation_Guide#45]
Running version 10.2.0. Changing zones and gaining rep in. at least. the new Emerald Dream zone is causing the following error to occur. Thanks.

24x ReputationGuide/ReputationGuide.lua:3372: table index is nil
[string "@ReputationGuide/ReputationGuide.lua"]:3372: in function `DumpReputationChangesToChat'
[string "@ReputationGuide/ReputationGuide.lua"]:384: in function `REP_OnEvent'
[string "*ReputationGuide.xml:11_OnEvent"]:1: in function <[string "*ReputationGuide.xml:11_OnEvent"]:1>
[string "=[C]"]: in function `REP_Orig_ExpandFactionHeader'
[string "@ReputationGuide/ReputationGuide.lua"]:1870: in function `ExpandFactionHeader'
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:297: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:289>
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:364: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:363>
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:427: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:426>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 ShowUpdateEntry = <function> defined @ReputationGuide/ReputationGuide.lua:3071
 LIMIT_TYPE_Gather = 4
 zone = <table> {
 }
 IsDeathKnight = false
 AfterCata = false
 Help = <function> defined @ReputationGuide/ReputationGuide.lua:1041
 Tailor = false
 AfterClassic = false
 has_value = <function> defined @ReputationGuide/ReputationGuide.lua:1028
 AfterShadowLands = false
 HIGHLIGHT_COLOUR = "|cFF00FF00"
 LIMIT_TYPE_Ench = 10
 SortByStandingWithFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4814
 OriginalRepOrderWithFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4947
 Expansions = <table> {
 }
 AfterTBC = false
 WatchedFactionDetails = <function> defined @ReputationGuide/ReputationGuide.lua:5074
 ExtractSkills = <function> defined @ReputationGuide/ReputationGuide.lua:4118
 LIMIT_TYPE_Aid = 13
 AfterDragonflight = false
 TestRepGain = <function> defined @ReputationGuide/ReputationGuide.lua:3210
 HELP_COLOUR = "|cFFFFFF7F"
 Incrip = false
 OriginalRepOrderWithoutFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4634
 SortByStandingWithoutFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4399
 ListByStanding = <function> defined @ReputationGuide/ReputationGuide.lua:4078
 Arch = false
 Rep_Detail_Frame = <function> defined @ReputationGuide/ReputationGuide.lua:3857
 LIMIT_TYPE_Skin = 2
 Engin = false
 GetReadyReputation = <function> defined @ReputationGuide/ReputationGuide.lua:3594
 ToggleDetailWindow = <function> defined @ReputationGuide/ReputationGuide.lua:3502
 Black = false
 Leath = false
 Skin = false
 Quest_Names = <function> defined @ReputationGuide/ReputationGuide.lua:1225
 InitItemName = <function> defined @ReputationGuide/ReputationGuide.lua:1191
 GetUpdateListSize = <function> defined @ReputationGuide/ReputationGuide.lua:3055
 AfterWoD = false
 LIMIT_TYPE_Tail = 8
 QUEST_COLOUR = "|cFFC0FFC0"
 REP_ExpansionFunctionsTable = <table> {
 }
 TableSize = <function> defined @ReputationGuide/ReputationGuide.lua:976
 LIMIT_TYPE_Jewel = 11
 InitFactionMap = <function> defined @ReputationGuide/ReputationGuide.lua:1364
 IsDragonflight = false
 LIMIT_TYPE_Engi = 5
 BAG_BANK_COLOUR = "|cFFFFFF7F"
 Enchan = false
 BAG_COLOUR = "|cFFC0FFC0"
 LIMIT_TYPE_Arch = 14
 LIMIT_TYPE_Fish = 16
 LIMIT_TYPE_Incr = 12
 Content = <function> defined @ReputationGuide/ReputationGuide.lua:1386
 InitMobName = <function> defined @ReputationGuide/ReputationGuide.lua:1150
 InitMapName = <function> defined @ReputationGuide/ReputationGuide.lua:1100
 Update_Tooltip = <function> defined @ReputationGuide/ReputationGuide.lua:2329
 About = <function> defined @ReputationGuide/ReputationGuide.lua:1056
 IsMoP = false
 RGBToColour_perc = <function> defined @ReputationGuide/ReputationGuide.lua:1024
 BoolToEnabled = <function> defined @ReputationGuide/ReputationGuide.lua:1017
 BFFLabels = <table> {
 }
 Concat = <function> defined @ReputationGuide/ReputationGuide.lua:1001
 GetWords = <function> defined @ReputationGuide/ReputationGuide.lua:985
 IsHuman = false
 GetTabardFaction = <function> defined @ReputationGuide/ReputationGuide.lua:1285
 IsClassic = false
 Debug = <function> defined @ReputationGuide/ReputationGuide.lua:971
 DumpTable = <function> defined @ReputationGuide/ReputationGuide.lua:450
 PrintSlash = <function> defined @ReputationGuide/ReputationGuide.lua:966
 Printtest = <function> defined @ReputationGuide/ReputationGuide.lua:962
 Print = <function> defined @ReputationGuide/Reputa

**Comment by imershon** [comment]
same

**Comment by tvlfrosty** [comment]
Quickly unlocked the Emerald Dream zone, hoping to dive deeper into the problem this weekend.

**Comment by tvlfrosty** [comment]
> Running version 10.2.0. Changing zones and gaining rep in. at least. the new Emerald Dream zone is causing the following error to occur. Thanks.



> same

Does it still happen? And does it happen after gaining rep from a specific activity? I am currently not getting any errors from switching zones, and gaining rep/renown after switching zones. Or does it happen after a specific rep/renown level?

**Comment by imershon** [comment]
In my case I get the errors on load - given the reference to /DataStore_Reputations it looks like conflict with Altoholic

**Comment by tvlfrosty** [comment]
> In my case I get the errors on load - given the reference to /DataStore_Reputations it looks like conflict with Altoholic

Yea I saw the line from DataStore_Reputations as well , I did try it with Altoholic active before I posted.

But I took a deeper look at the code of both addons, and I think I found the issue.
I am going to do some more testing tonight, and hopefully can figure out a fix!

**Comment by tvlfrosty** [comment]
@imershon or @Ookami313, what does your chat show when you type: `/dump REP_Data.Global.SortByStanding`?

Does it show `[1] = false`, or does it show `[1] = true`?

If it says true it could be a reason why I personally don't get the error, if it says false I will have to look and test some more stuff.

**Comment by imershon** [comment]
Getting a false here

**Comment by tvlfrosty** [comment]
> Getting a false here

Alright, thanks for letting me know! I will keep testing, hopefully I will find a fix soon, apologies for the inconvenience in the meantime!

**Comment by imershon** [comment]
No probs take your time :) - lua can be annoying - I've just tried disabling altoholic, datastore, and allthethings - still getting false from the REP_Data.Global.SortByStanding - not sure it'll help much but my locals are naturally the same as Ookami313 however due to addon differences my strings with the above addons disabled at load is

36x ReputationGuide/ReputationGuide.lua:3372: table index is nil
[string "@ReputationGuide/ReputationGuide.lua"]:3372: in function `DumpReputationChangesToChat'
[string "@ReputationGuide/ReputationGuide.lua"]:384: in function `REP_OnEvent'
[string "*ReputationGuide.xml:11_OnEvent"]:1: in function <[string "*ReputationGuide.xml:11_OnEvent"]:1>
[string "=[C]"]: in function `REP_Orig_ExpandFactionHeader'
[string "@ReputationGuide/ReputationGuide.lua"]:1870: in function `ExpandFactionHeader'
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:329: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:321>
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:396: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:395>
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:473: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:472>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by tvlfrosty** [comment]
> No probs take your time :) - lua can be annoying - I've just tried disabling altoholic, datastore, and allthethings - still getting false from the REP_Data.Global.SortByStanding - not sure it'll help much but my locals are naturally the same as Ookami313 however due to addon differences my strings with the above addons disabled at load is

It does look like there is some old errors in there still, since it's still mentioning "DataStore_Reputations". I did however make a small change to the code that I think was conflicting between the 2 addons just in case it was causing issues. it's currently uploading to curseforge together with some other small fixes.

But if it's still causing isses even with all those addons disabled I am not sure what's causing the issue just yet, but I will definitely keep looking/testing!

**Comment by Ookami313** [comment]
Sorry, was out of town for the holiday and just got home. I'll update to the newest version and see if issue are still occurring. Thanks for the time you put into this.

**Comment by Galandel** [comment]
Sadly, I am still receiving the error post update. It did move a few lines though:
`4x ReputationGuide/ReputationGuide.lua:3383: table index is nil
[string "@ReputationGuide/ReputationGuide.lua"]:3383: in function `DumpReputationChangesToChat'
[string "@ReputationGuide/ReputationGuide.lua"]:384: in function `REP_OnEvent'
[string "*ReputationGuide.xml:11_OnEvent"]:1: in function <[string "*ReputationGuide.xml:11_OnEvent"]:1>
[string "=[C]"]: in function `REP_Orig_ExpandFactionHeader'
[string "@ReputationGuide/ReputationGuide.lua"]:1871: in function `ExpandFactionHeader'
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:329: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:321>
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:396: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:395>
[string "@DataStore_Reputations/DataStore_Reputations.lua"]:473: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:472>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 ShowUpdateEntry = <function> defined @ReputationGuide/ReputationGuide.lua:3075
 LIMIT_TYPE_Gather = 4
 zone = <table> {
 }
 IsDeathKnight = false
 AfterCata = false
 Help = <function> defined @ReputationGuide/ReputationGuide.lua:1042
 Tailor = false
 AfterClassic = false
 has_value = <function> defined @ReputationGuide/ReputationGuide.lua:1029
 AfterShadowLands = false
 HIGHLIGHT_COLOUR = "|cFF00FF00"
 LIMIT_TYPE_Ench = 10
 SortByStandingWithFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4822
 OriginalRepOrderWithFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4955
 Expansions = <table> {
 }
 AfterTBC = false
 WatchedFactionDetails = <function> defined @ReputationGuide/ReputationGuide.lua:5082
 ExtractSkills = <function> defined @ReputationGuide/ReputationGuide.lua:4126
 LIMIT_TYPE_Aid = 13
 AfterDragonflight = false
 TestRepGain = <function> defined @ReputationGuide/ReputationGuide.lua:3214
 HELP_COLOUR = "|cFFFFFF7F"
 Incrip = false
 OriginalRepOrderWithoutFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4642
 SortByStandingWithoutFactionHeader = <function> defined @ReputationGuide/ReputationGuide.lua:4407
 ListByStanding = <function> defined @ReputationGuide/ReputationGuide.lua:4086
 Arch = false
 Rep_Detail_Frame = <function> defined @ReputationGuide/ReputationGuide.lua:3865
 LIMIT_TYPE_Skin = 2
 Engin = false
 GetReadyReputation = <function> defined @ReputationGuide/ReputationGuide.lua:3602
 ToggleDetailWindow = <function> defined @ReputationGuide/ReputationGuide.lua:3513
 Black = false
 Leath = false
 Skin = false
 Quest_Names = <function> defined @ReputationGuide/ReputationGuide.lua:1226
 InitItemName = <function> defined @ReputationGuide/ReputationGuide.lua:1192
 GetUpdateListSize = <function> defined @ReputationGuide/ReputationGuide.lua:3059
 AfterWoD = false
 LIMIT_TYPE_Tail = 8
 QUEST_COLOUR = "|cFFC0FFC0"
 REP_ExpansionFunctionsTable = <table> {
 }
 TableSize = <function> defined @ReputationGuide/ReputationGuide.lua:977
 LIMIT_TYPE_Jewel = 11
 InitFactionMap = <function> defined @ReputationGuide/ReputationGuide.lua:1365
 IsDragonflight = false
 LIMIT_TYPE_Engi = 5
 BAG_BANK_COLOUR = "|cFFFFFF7F"
 Enchan = false
 BAG_COLOUR = "|cFFC0FFC0"
 LIMIT_TYPE_Arch = 14
 LIMIT_TYPE_Fish = 16
 LIMIT_TYPE_Incr = 12
 Content = <function> defined @ReputationGuide/ReputationGuide.lua:1387
 InitMobName = <function> defined @ReputationGuide/ReputationGuide.lua:1151
 InitMapName = <function> defined @ReputationGuide/ReputationGuide.lua:1101
 Update_Tooltip = <function> defined @ReputationGuide/ReputationGuide.lua:2333
 About = <function> defined @ReputationGuide/ReputationGuide.lua:1057
 IsMoP = false
 RGBToColour_perc = <function> defined @ReputationGuide/ReputationGuide.lua:1025
 BoolToEnabled = <function> defined @ReputationGuide/ReputationGuide.lua:1018
 BFFLabels = <table> {
 }
 Concat = <function> defined @ReputationGuide/ReputationGuide.lua:1002
 GetWords = <function> defined @ReputationGuide/ReputationGuide.lua:986
 IsHuman = false
 GetTabardFaction = <function> defined @ReputationGuide/ReputationGuide.lua:1286
 IsClassic = false
 Debug = <function> defined @ReputationGuide/ReputationGuide.lua:972
 DumpTable = <function> defined @ReputationGuide/ReputationGuide.lua:450
 PrintSlash = <function> defined @ReputationGuide/ReputationGuide.lua:967
 Printtest = <function> defined @ReputationGuide/ReputationGuide.lua:963
 Print = <function> defined @ReputationGuide/Reputa`

**Comment by Galandel** [comment]
I also did the dump command and mine also shows false.

**Comment by imershon** [comment]
After the last update it's no longer hitting the datastores now although those addons are still disabled and still a false on the dump

6x ReputationGuide/ReputationGuide.lua:3383: table index is nil
[string "@ReputationGuide/ReputationGuide.lua"]:3383: in function `DumpReputationChangesToChat'
[string "@ReputationGuide/ReputationGuide.lua"]:634: in function `Init'
[string "@ReputationGuide/ReputationGuide.lua"]:428: in function `REP_OnEvent'
[string "*ReputationGuide.xml:11_OnEvent"]:1: in function <[string "*ReputationGuide.xml:11_OnEvent"]:1>

**Comment by tvlfrosty** [comment]
> Sorry, was out of town for the holiday and just got home. I'll update to the newest version and see if issue are still occurring. Thanks for the time you put into this.
> 
> Edit: Ran the /dump script that was posted, resulted in a [1]= false return.

Ahh no worries, Thanks for the update!

> I also did the dump command and mine also shows false.

Thanks for the update as well!


> After the last update it's no longer hitting the datastores now although those addons are still disabled and still a false on the dump

Hmm, interesting that the disabled addons now don't show anymore where before they did, assuming it was just an old message before because it was bundeling the errors with previous errors.

Tomorrow morning I will start doing more testing/debugging for this issue.

**Comment by Galandel** [comment]
Update from me, but I haven't seen this issue pop up since the 10.2.2-release update. Thanks for your hard work, it is much appreciated.

**Comment by tvlfrosty** [comment]
> Update from me, but I haven't seen this issue pop up since the 10.2.2-release update. Thanks for your hard work, it is much appreciated.

That's very good to hear! Is it also fixed for you @Ookami313? If so I will mark the issue as resolved.

**Comment by Ookami313** [comment]
I have not had any issue since the update to 10.2.2, so I will assume that the issue has been fixed (Thank you). Feel free to close this and if it rears its ugly head again I'll open another ticket. Thanks again.

**Comment by imershon** [comment]
Can't get it to error anymore either - thanks for looking into it much appreciated.

**Comment by tvlfrosty** [comment]
Awesome! Thanks for all the error logs and feedback!
