### ISSUE TITLE
[request] (SoD) Silverwing Sentinels/League of Arathor new quests doesn't show up on their guides.

### ISSUE THREAD

**Issue by trunksq** [tvlfrosty/Reputation_Guide#46]
Hi! The current Classic Season of Discovery build doesn't support the new quests added to the game that gives reputation to the PvP factions.

For League of Arathor (Arathi Basin), it's missing this quest that gives 200+ rep: https://www.wowhead.com/classic/quest=79990/stranglethorn-lumber

And for Silverwing Sentinels (Warsong Gulch) its missing the reputation gains from the Ashenvale event:
https://www.wowhead.com/classic/guide/season-of-discovery/battle-for-ashenvale-world-pvp-event

**Comment by tvlfrosty** [comment]
Thanks for letting me know, I don't play season of discovery myself so not fully up-to-date with newly added stuff, but I will add it to the addon for sure!

**Comment by tvlfrosty** [comment]
File is being uploaded to Curse, let me know if everything is working as expected once it's approved!

**Comment by trunksq** [comment]
Working perfectly, all the new available reputation gains are showing up! Haven't seen on the horde side for their PvP factions yet tho, might check that later aswell but Alliance is showing everything up perfectly.

![repguide](https://github.com/tvlfrosty/Reputation_Guide/assets/162748954/684d5441-2fc9-4bc0-a002-0b8de78c9457)

Thank you very much for this awesome addon! Appreciate the effort into updating it for the SoD people!
