### ISSUE TITLE
Quests are not being displayed

### ISSUE THREAD

**Issue by maddocx** [tvlfrosty/Reputation_Guide#47]
In classic, the quest list shows some number of quests, then "Quest name not available. QuestID: xxxx" . 

e.g. "558x Quest name not available. QuestID: 8842"

![Screenshot 2024-03-12 142604](https://github.com/tvlfrosty/Reputation_Guide/assets/163201403/e360c17e-8ca1-4a91-a56d-bbb9511a49cf)

**Comment by tvlfrosty** [comment]
Hey, which version of classic are you playing on? Classic Era, Season of Discovery or Wrath of the lich king?

**Comment by maddocx** [comment]
Oh whoops, Season of Discovery.

**Comment by tvlfrosty** [comment]
I have disabled the specific quests for now, I have been meaning to work out some sort of phase check, those quests are only active during the AQ war effort event, and might not even be active in Season of Discovery, so I might have to make some sort of filter for that.

Seeing as making a filter and check on phase is going to take some more time I will make a seperate issue for that myself, the quests should no longer be visible in the release that is currently being uploaded to Curse, once it's approved I will check it and close this specific issue.

Hopefully I can work out a permanent solution for these kind of quests soon.
