### ISSUE TITLE
REP Options Frame

### ISSUE THREAD

**Issue by Brum8842** [tvlfrosty/Reputation_Guide#61]
Getting this error when logging into the game

Addon version: 1.0.6-release 
Game version: 4.4.0

Date: 2024-05-19 08:22:52
ID: 1
Error occured in: Global
Count: 1
Message: ...rface/AddOns/ReputationGuide/ReputationGuideSkin.lua line 40:
   attempt to index global 'REP_OptionsFrame' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ReputationGuide/ReputationGuideSkin.lua"]:40: in main chunk
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by tvlfrosty** [comment]
Should be fixed in the 1.0.7-release that's currently being processed on curse, the github should also be fulled updated with the latest changes.
