### ISSUE TITLE
Issue thread for The War Within

### ISSUE THREAD

**Issue by tvlfrosty** [tvlfrosty/Reputation_Guide#63]
I am sure there will be plenty of issues coming with the release of The War Within expansion, I will make a full list here and hopefully I can fix all of them eventually.

- [x] Move global reputation functions to their respected namespace C_Reputations, such as GetNumFactions and GetSelectedFaction.
- [x] Fix detail window, as onclick is no longer properly working.
- [x] Fix DumpReputationChangesToChat() for reputation changes.
- [x] Fix the data within the datail window, as everything is currently empty.
- [x] Fix the REP_BuildUpdateList() as it's not yet properly building the reputation lists.
- [x] Fix the "View Renown" button in the Detail frame.
- [x] Add /rep watch <factionID> for tww, since "C_Reputation.SetWatchedFactionByID" is now available.
- [x] Whenever "ReputationFrameMixin" is hidden/not shown the reputation events for printing reputation are being unregistered, so have to check how the reputation is normally still shown in the chat without the addon.
- [x] Fix some faction's detail list as it shows x10000 for certain items giving 1 rep when it's only 3000 rep total.
- [x] Fix the positioning of the options button
- [x] Add The War Within factions
- [x] #85
- [x] SortByStanding functionality based on reputation levels (factions with only 6 reputation levels)
- [x] Reputation values printed to chat based on reputation levels (Paragon reputations, or factions with other Standing labels)
- [x] 10.0.2.3 Renown Reputation gains go off-chart sometimes (perhaps due to quest giving more than 2500 renown)
- [x] Friendship reputations for Warband isn't counting the reputation items correctly adds a negative value instead.
- [x] ReputationDetailFrame sometimes randomly resets the SelectedFaction so the list of items shows up empty

**Comment by tvlfrosty** [comment]
If you have access to the Alpha / Beta for The War Within and come across anything that doesn't seem correct or any bugs, let me know here.

**Comment by tvlfrosty** [comment]
Making some progress, as the detail window now properly toggles when clicking the reputationbar / factions.

![WowB_CVlUQv2RhF](https://github.com/tvlfrosty/Reputation_Guide/assets/8556252/0f814796-ce03-478e-82d1-e7b4dbc29880)

The next step will be to slowly fix all the data within the detail window.

**Comment by tvlfrosty** [comment]
New fix for TWW pre-patch coming later today.


known issues atm are that the checkboxes in the detailframe aren't working as expected due to the getSelectedFaction not returning the correct faction id.

This can be bypassed by running /rep watchid <factionID> once the update is pushed to curse.

**Comment by rursache** [comment]
addon is still broken in 11.0.2

- having the rep bar appear when you get rep is not working
- advanced rep stats in chat is not working

both need to be disabled to see rep gain in chat at all

**Comment by tvlfrosty** [comment]
I will have a look at the issues with 11.0.2, it seems the warband factions behave differently than normal factions with the reputation triggers.

**Comment by tvlfrosty** [comment]
I found a temporary fix for the addon not showing the reputation changes in the chat I will post a new version later today. After that I will try and work on a permanent fix for the issue.

**Comment by rursache** [comment]
the latest update made the game load super slow with the addon active. please use BugGrabber and BugSack to investigate, i had to turn the addon off to not wait 15 seconds in each loading screen

**Comment by tvlfrosty** [comment]
@rursache I use both BugGrabber and BugSack, And I am investigating the issue as we speak #79. Not sure why it's causing an issue for some people while I personally don't have the issue.

But apologies for the inconvenience, hopefully I will have it fixed and sorted soon...

**Comment by rursache** [comment]
thank you for your effort!

**Comment by tvlfrosty** [comment]
Main issues are fixed, hopefully now that the biggest issues are sorted for The War Within, I will find some time to look at sortByStanding functionality again...

If you come across any other issues, don't hesitate to create a new issue for it.
