### ISSUE TITLE
Constant Reputation updates since v1.0.8

### ISSUE THREAD

**Issue by Saprobie** [tvlfrosty/Reputation_Guide#66]
Playing DF whenever I load into the game, use a portal/hearthstone or gain reputation I get the following spammed in my chat window

![image](https://github.com/tvlfrosty/Reputation_Guide/assets/40485507/f95d5a12-0ea6-4781-b2f4-3d1853a1ce67)
I'm paragon rep with all DF faction renowns and this happens when I use either a rep token or gain rep via a world quest.

The same occurs when I only have this addon enabled.
It has only started occurring since updating to 1.0.8 this morning.

I've just portaled from ValyD to Orgrimmar and...

![image](https://github.com/tvlfrosty/Reputation_Guide/assets/40485507/c87622e6-14cb-47ac-8eea-2235ff0f274f)

Can this be disabled/hidden. I'm going to revert back to previous version for now.

**Comment by tvlfrosty** [comment]
I will have a look at it right away!

**Comment by tvlfrosty** [comment]
In the 1.1.1 release the spam should be fully gone, additionally Renown factions that hit paragon level should now properly track once again.

If the update for 1.1.1 does not show up soon I will check if the issues I had with the .toc files is still causing trouble and hopefully fix it asap.
