### ISSUE TITLE
Still getting a Lua error in Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [tvlfrosty/Reputation_Guide#86]
On the latest.

13x ...rfaceReputationGuide/ReputationGuideSkin.lua:57: attempt to index global 'REP_ReputationDetailFrame' (a nil value)
[string "@ReputationGuide/ReputationGuideSkin.lua"]:57: in main chunk

Locals:
addonName = "ReputationGuide"
REP = <table> {
 IsClassicPhaseFour = false
 LIMIT_TYPE_Incr = 12
 NEW_STANDING_COLOUR = "|cFF6060C0"
 ShowDragonflightPhaseThree = false
 AfterClassic = false
 ShowClassicSOMPhaseFour = false
 IsTheLastTitan = false
 Expansions = <table> {
 }
 IsClassicSOMPhaseFour = false
 IsAlliance = false
 IsClassicPhaseThree = false
 IsCataPhaseFour = false
 ShowLegionPhaseThree = false
 ShowWotlkPhaseFour = false
 IsTheWarWithin = false
 ShowTBCPhaseTwo = false
 IsCataPhaseThree = false
 GameBuildVersion = 11504
 IsWoDPhaseTwo = false
 IsMoP = false
 ShowClassicPhaseFive = true
 ShowClassicSODPhaseFive = true
 ShowBfAPhaseFour = false
 IsClassic = true
 ShowCataPhaseThree = false
 LIMIT_TYPE_Mine = 3
 AfterWotlk = false
 IsClassicSODPhaseFive = true
 IsLegionPhaseTwo = false
 IsHeroic = false
 IsTheWarWithinPhaseOne = false
 IsMidnight = false
 MaxFactionReputation = <table> {
 }
 IsShadowLandsPhaseTwo = false
 IsClassicSODPhaseTwo = false
 LOWLIGHT_COLOUR = "|cFFFF3F3F"
 LIMIT_TYPE_Alch = 6
 ShowShadowLandsPhaseTwo = false
 AfterLegion = false
 IsClassicSOM = false
 IsClassicSODPhaseFour = false
 AfterShadowLands = false
 IsWotlkPhaseOne = false
 ShowWotlkPhaseThree = false
 IsClassicPhaseSix = true
 ShowBfAPhaseTwo = false
 IsShadowLandsPhaseOne = false
 IsLegionPhaseThree = false
 ShowClassicSODPhaseThree = true
 ShowMoPPhaseThree = false
 Enchan = false
 ShowDragonflightPhaseOne = false
 LIMIT_TYPE_Arch = 14
 IsShadowLandsPhaseThree = false
 ShowTheWarWithinPhaseOne = false
 BFFLabels = <table> {
 }
 IsBfAPhaseThree = false
 IsClassicSODPhaseOne = false
 ShowWoDPhaseThree = false
 NEW_REP_COLOUR = "|cFF7F7FFF"
 FACTION_BAR_COLORS = <table> {
 }
 ShowWotlkPhaseTwo = false
 ShowClassicPhaseTwo = true
 IsMoPPhaseFive = false
 IsMoPPhaseOne = false
 IsBfA = false
 Alche = false
 Mine = false
 ShowTBCPhaseFive = false
 ShowTheLastTitanPhaseOne = false
 Engin = false
 IsWoDPhaseOne = false
 ShowMoPPhaseTwo = false
 IsMoPPhaseFour = false
 IsHorde = false
 LIMIT_TYPE_Gather = 4
 AfterCata = false
 ShowClassicPhaseFour = true
 IsDragonflightPhaseOne = false
 HIGHLIGHT_COLOUR = "|cFF00FF00"
 LIMIT_TYPE_Ench = 10
 IsLegion = false
 ShowTBCPhaseOne = false
 LIMIT_TYPE_Aid = 13
 AfterDragonflight = false
 IsClassicSOMPhaseOne = false
 Incrip = false
 LIMIT_TYPE_Skin = 2
 IsWotlkPhaseThree = false
 Skin = false
 QUEST_COLOUR = "|cFFC0FFC0"
 ShowShadowLandsPhaseOne = false
 LIMIT_TYPE_Engi = 5
 AfterBfA = false
 IsShadowLands = false
 LIMIT_TYPE_Fish = 16
 Factions = <table> {
 }
 IsClassicSODPhaseThree = false
 Leath = false
 ShowMoPPhaseFive = false
 ShowClassicSODPhaseTwo = true
 IsClassicPhaseFive = false
 IsWotlkPhaseFive = false
 LIMIT_TYPE_Blac = 7
 QUEST_ACTIVE_COLOUR = "|cFFFF7F7F"
 IsCata = false
 ShowClassicPhaseSix = true
 Jewel = false
 IsTBCPhaseTwo = false
 IsCataPhaseTwo = false
 ShowShadowLandsPhaseThree = false
 AfterWoD = false
 IsDeathKnight = false
 IsBfAPhaseOne = false
 IsTBCPhaseThree = false
 Tailor = false
 ShowTBCPhaseFour = false
 IsMoPPhaseTwo = false
 LIMIT_TYPE_Tail = 8
 ShowWotlkPhaseOne = false
 ShowClassicSOMPhaseThree = false
 IsCataPhaseOne = false
 IsClassicSOD = false
 Arch = false
 IsTBCPhaseFour = false
 IsClassicSOMPhaseThree = false
 ShowWotlkPhaseFive = false
 IsWotlkPhaseTwo = false
 ShowCataPhaseTwo = false
 AfterTheWarWithin = false
 MaxFactionLevel = <table> {
 }
 ShowMidnightPhaseOne = false
 ShowWoDPhaseFour = false
 Cook = false
 IsTBCPhaseFive = false
 LIMIT_TYPE_Jewel = 11
 IsDragonflightPhaseTwo = false
 BAG_BANK_COLOUR = "|cFFFFFF7F"
 Black = false
 AfterTBC = false
 IsBfAPhaseTwo = false
 ShowLegionPhaseTwo = false
 ShowTBCPhaseThree = false
 ShowClassicPhaseOne = true
 BAG_COLOUR = "|cFFC0FFC0"
 ShowWoDPhaseTwo = false
 ShowWoDPhaseOne = false
 IsMidnightPhaseOne = false
 AfterTheLastTitan = false
 IsMoPPhaseThree = false
 IsHuman = false
 ShowClassicPhaseThree = true
 IsWoDPhaseThree = false
 ShowBfAPhaseOne = false
 IsDragonflight = false
 HasTradingPost = false
 ShowBfAPhaseThree = false
 ShowCataPhaseFour = false
 LIMIT_TYPE_Leat = 9
 IsTBCPhaseOne =

**Comment by MatthewRyanRead** [comment]
This is happening in TWW as well.  The latest version is trying to access several globals that it never initializes.

**Comment by tvlfrosty** [comment]
Thanks for letting me know, I personally don't use ElvUI, so never got the error, will check what's wrong with the initialization, will fix it as soon as possible.

**Comment by tvlfrosty** [comment]
Oke "1.2.6-release" is being uploaded now, it should at least fix the error caused by the changes made in combination with ElvUI, I will however have to do more work to make it look good with ElvUI again, so I will keep this issue open for now till it's fixed again.

I downloaded ElvUI for SOD for personal testing.

![WowClassic_jmMp6lEtPH](https://github.com/user-attachments/assets/ea58e56e-c89e-47b8-9879-72a61da54af0)

**Comment by tvlfrosty** [comment]
Oke this looks more like how it used to look I believe:
![WowClassic_8PrL8KXFp9](https://github.com/user-attachments/assets/95d8a516-c06f-4742-b092-1faef769ea74)

**Comment by tvlfrosty** [comment]
Looking at retail now, since there might be some more errors there... Apologies

**Comment by Gogo1951** [comment]
Didn't realize it was an Elv conflict, thanks for sorting that out! (=

**Comment by tvlfrosty** [comment]
Alright, "1.2.7-release" is being uploaded to Curse right now, this should fix all issues regarding ElvUI for SOD/Retail. If there is any further issues with that release please let me know!

**Comment by Gogo1951** [comment]
Works great, thanks!
