### ISSUE TITLE
bug 20th celeb version

### ISSUE THREAD

**Issue by Addonman** [tvlfrosty/Reputation_Guide#87]
as i loged in i got this error
Message: ...ddOns/ReputationGuide/ReputationGuideDetailFrame.lua line 31:
   attempt to index global 'REP_DetailFirstDivider' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ReputationGuide/ReputationGuideDetailFrame.lua"]:31: ChangeReputationDetailFrameUI()
   [string "@Interface/AddOns/ReputationGuide/ReputationGuide.lua"]:864: MakeUIChanges()
   [string "@Interface/AddOns/ReputationGuide/ReputationGuide.lua"]:244: REP_OnEvent()
   [string "*ReputationGuide.xml:13_OnEvent"]:1:
      [string "*ReputationGuide.xml:13_OnEvent"]:1

**Comment by Starlynk1** [comment]
Same error message. Didn't open the Rep Guide panel, so not sure if that is messed up. But didn't seem to affect anything when just playing.

**Comment by tvlfrosty** [comment]
I will have a look at it as soon as the servers are back up, seems they are down at the moment for me.

**Comment by tvlfrosty** [comment]
Alright, seems like they added a scrollbar to the detailfame that was causing some issues.

![Wow_RWYXC7tlJF](https://github.com/user-attachments/assets/ee78a338-52b3-4659-a3b5-779c00675d9e)

Will update the addon to 11.0.5 with the fix soon

**Comment by tvlfrosty** [comment]
Issue should be fixed in the 1.2.9-release that is currently being uploaded to Curse.
If there is any further issues please let me know!
